// Code generated by ./testdata/zblk_test_gen.py; DO NOT EDIT.
package zdata

import "lab.nexedi.com/kirr/neo/go/zodb"

const zf_blksize = 2097152
const zf_size    = 8388608
const z0_oid     = zodb.Oid(2)
const z1_oid     = zodb.Oid(3)
const zf_oid     = zodb.Oid(1)
const z0_rev     = zodb.Tid(0x285cbac3851eb99)
const z1_rev     = zodb.Tid(0x285cbac3851eb99)
const z0_len     = 16384
const z1_htlen   = 131072
