// Code generated by testdata/zblk_test_gen.py; DO NOT EDIT.
package zdata

import "lab.nexedi.com/kirr/neo/go/zodb"

func init() {
	zblkTestDataRegistry["py2_pickle1"] = ZBlkTestData{
		data_fs    : "testdata/py2_pickle1/zblk.fs",
		zf_blksize : 2097152,
		zf_size    : 8388608,
		z0_oid     : zodb.Oid(2),
		z1_oid     : zodb.Oid(3),
		zf_oid     : zodb.Oid(1),
		z0_rev     : zodb.Tid(0x285cbac3851eb99),
		z1_rev     : zodb.Tid(0x285cbac3851eb99),
		z0_len     : 16384,
		z1_htlen   : 131072,
	}
}
